#!/usr/bin/env bash

echo "compile document like this:
  compile sbol3
"
VERSION=sbol3

pdflatex "${VERSION}"
bibtex "${VERSION}"
pdflatex "${VERSION}"
echo ""
echo "============FINAL LATEX RUN==========="
echo ""
pdflatex "${VERSION}"
